name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  API: 24 
  TARGET: aarch64-linux-android

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Checkout repo 
        uses: actions/checkout@v4 
        
      - name: Install build tools 
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison re2c libxml2-dev pkg-config build-essential curl unzip git

        
      - name: Download Android NDK 
        run: | 
          wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip 
          unzip android-ndk-r27-linux.zip 
          echo "NDK=$PWD/android-ndk-r27" >> $GITHUB_ENV 
          echo "TOOLCHAIN=$PWD/android-ndk-r27/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV 
          
      - name: Clone PHP source 
        run: | 
          git clone https://github.com/php/php-src.git 
          cd php-src 
          git checkout PHP-8.3 
         
          cat <<'EOF' > android_compat.h
              #ifndef PHP_ANDROID_COMPAT_H
              #define PHP_ANDROID_COMPAT_H
              
              #ifdef ANDROID
              
              #include <unistd.h>
              #include <sys/types.h>
              
              #ifndef getdtablesize
              #define getdtablesize() sysconf(_SC_OPEN_MAX)
              #endif
              
              #ifndef daemon
              static inline int daemon(int nochdir, int noclose) { return -1; }
              #endif
              
              #endif
              
              #endif          
            EOF

          sed -i '1i #include "android_compat.h"' main/php.h

      
      - name: Configure PHP 
        run: | 
          cd php-src 
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang 
          export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++ 
          
          ./buildconf --force 
          
          ./configure --host=$TARGET --enable-embed --disable-all --disable-dns --disable-mailparse --enable-json
            
      - name: Build PHP 
        run: | 
          cd php-src 
          make -j$(nproc) 
          
      - name: Collect artifacts 
        run: | 
          mkdir artifacts 
          cp php-src/libs/libphp.so artifacts/ 
          cp -r php-src/sapi/embed artifacts/headers 
          
      - name: Upload PHP embed build 
        uses: actions/upload-artifact@v4 
        with: 
          name: php-android-embed 
          path: artifacts
